spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "sheetsync"

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgres.Driver
    pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

